// Code generated by "stringer -type=ImpinjCustomMessageType,ImpinjCustomParamType -linecomment -output impinj_string.go"; DO NOT EDIT.

package llrp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgImpinjEnableExtensions-21]
	_ = x[MsgImpinjEnableExtensionsResponse-22]
	_ = x[MsgImpinjSaveSettings-23]
	_ = x[MsgImpinjSaveSettingsResponse-24]
}

const _ImpinjCustomMessageType_name = "ImpinjEnableExtensionsImpinjEnableExtensionsResponseImpinjSaveSettingsImpinjSaveSettingsResponse"

var _ImpinjCustomMessageType_index = [...]uint8{0, 22, 52, 70, 96}

func (i ImpinjCustomMessageType) String() string {
	i -= 21
	if i >= ImpinjCustomMessageType(len(_ImpinjCustomMessageType_index)-1) {
		return "ImpinjCustomMessageType(" + strconv.FormatInt(int64(i+21), 10) + ")"
	}
	return _ImpinjCustomMessageType_name[_ImpinjCustomMessageType_index[i]:_ImpinjCustomMessageType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParamImpinjRequestedData-21]
	_ = x[ParamImpinjSubRegulatoryRegion-22]
	_ = x[ParamImpinjInventorySearchMode-23]
	_ = x[ParamImpinjFixedFrequencyList-26]
	_ = x[ParamImpinjReducedPowerFrequencyList-27]
	_ = x[ParamImpinjLowDutyCycle-28]
	_ = x[ParamImpinjDetailedVersion-29]
	_ = x[ParamImpinjFrequencyCapabilities-30]
	_ = x[ParamImpinjGPIDebounceConfiguration-36]
	_ = x[ParamImpinjReaderTemperature-37]
	_ = x[ParamImpinjLinkMonitorConfiguration-38]
	_ = x[ParamImpinjReportBufferConfiguration-39]
	_ = x[ParamImpinjAccessSpecConfiguration-40]
	_ = x[ParamImpinjBlockWriteWordCount-41]
	_ = x[ParamImpinjBlockPermalock-42]
	_ = x[ParamImpinjBlockPermalockOpSpecResult-43]
	_ = x[ParamImpinjGetBlockPermalockStatus-44]
	_ = x[ParamImpinjGetBlockPermalockStatusOpSpecResult-45]
	_ = x[ParamImpinjSetQTConfig-46]
	_ = x[ParamImpinjSetQTConfigOpSpecResult-47]
	_ = x[ParamImpinjGetQTConfig-48]
	_ = x[ParamImpinjGetQTConfigOpSpecResult-49]
	_ = x[ParamImpinjTagReportContentSelector-50]
	_ = x[ParamImpinjEnableSerializedTID-51]
	_ = x[ParamImpinjEnableRFPhaseAngle-52]
	_ = x[ParamImpinjEnablePeakRSSI-53]
	_ = x[ParamImpinjEnableGPSCoordinates-54]
	_ = x[ParamImpinjSerializedTID-55]
	_ = x[ParamImpinjRFPhaseAngle-56]
	_ = x[ParamImpinjPeakRSSI-57]
	_ = x[ParamImpinjGPSCoordinates-58]
	_ = x[ParamImpinjLoopSpec-59]
	_ = x[ParamImpinjGPSNMEASentences-60]
	_ = x[ParamImpinjGGASentence-61]
	_ = x[ParamImpinjRMCSentence-62]
	_ = x[ParamImpinjOpSpecRetryCount-63]
	_ = x[ParamImpinjAdvancedGPOConfiguration-64]
	_ = x[ParamImpinjEnableOptimizedRead-65]
	_ = x[ParamImpinjAccessSpecOrdering-66]
	_ = x[ParamImpinjEnableRFDopplerFrequency-67]
	_ = x[ParamImpinjRFDopplerFrequency-68]
	_ = x[ParamImpinjInventoryConfiguration-69]
	_ = x[ParamImpinjEnableTxPower-72]
	_ = x[ParamImpinjTxPower-73]
}

const (
	_ImpinjCustomParamType_name_0 = "ImpinjRequestedDataImpinjSubRegulatoryRegionImpinjInventorySearchMode"
	_ImpinjCustomParamType_name_1 = "ImpinjFixedFrequencyListImpinjReducedPowerFrequencyListImpinjLowDutyCycleImpinjDetailedVersionImpinjFrequencyCapabilities"
	_ImpinjCustomParamType_name_2 = "ImpinjGPIDebounceConfigurationImpinjReaderTemperatureImpinjLinkMonitorConfigurationImpinjReportBufferConfigurationImpinjAccessSpecConfigurationImpinjBlockWriteWordCountImpinjBlockPermalockImpinjBlockPermalockOpSpecResultImpinjGetBlockPermalockStatusImpinjGetBlockPermalockStatusOpSpecResultImpinjSetQTConfigImpinjSetQTConfigOpSpecResultImpinjGetQTConfigImpinjGetQTConfigOpSpecResultImpinjTagReportContentSelectorImpinjEnableSerializedTIDImpinjEnableRFPhaseAngleImpinjEnablePeakRSSIImpinjEnableGPSCoordinatesImpinjSerializedTIDImpinjRFPhaseAngleImpinjPeakRSSIImpinjGPSCoordinatesImpinjLoopSpecImpinjGPSNMEASentencesImpinjGGASentenceImpinjRMCSentenceImpinjOpSpecRetryCountImpinjAdvancedGPOConfigurationImpinjEnableOptimizedReadImpinjAccessSpecOrderingImpinjEnableRFDopplerFrequencyImpinjRFDopplerFrequencyImpinjInventoryConfiguration"
	_ImpinjCustomParamType_name_3 = "ImpinjEnableTxPowerImpinjTxPower"
)

var (
	_ImpinjCustomParamType_index_0 = [...]uint8{0, 19, 44, 69}
	_ImpinjCustomParamType_index_1 = [...]uint8{0, 24, 55, 73, 94, 121}
	_ImpinjCustomParamType_index_2 = [...]uint16{0, 30, 53, 83, 114, 143, 168, 188, 220, 249, 290, 307, 336, 353, 382, 412, 437, 461, 481, 507, 526, 544, 558, 578, 592, 614, 631, 648, 670, 700, 725, 749, 779, 803, 831}
	_ImpinjCustomParamType_index_3 = [...]uint8{0, 19, 32}
)

func (i ImpinjCustomParamType) String() string {
	switch {
	case 21 <= i && i <= 23:
		i -= 21
		return _ImpinjCustomParamType_name_0[_ImpinjCustomParamType_index_0[i]:_ImpinjCustomParamType_index_0[i+1]]
	case 26 <= i && i <= 30:
		i -= 26
		return _ImpinjCustomParamType_name_1[_ImpinjCustomParamType_index_1[i]:_ImpinjCustomParamType_index_1[i+1]]
	case 36 <= i && i <= 69:
		i -= 36
		return _ImpinjCustomParamType_name_2[_ImpinjCustomParamType_index_2[i]:_ImpinjCustomParamType_index_2[i+1]]
	case 72 <= i && i <= 73:
		i -= 72
		return _ImpinjCustomParamType_name_3[_ImpinjCustomParamType_index_3[i]:_ImpinjCustomParamType_index_3[i+1]]
	default:
		return "ImpinjCustomParamType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
